services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - "checklistnetwork"
    volumes:
      - "checklistdata:/var/lib/postgresql/data"
    ports:
      - "2345:5432"
    restart: unless-stopped
  frontend:
    build: 
      context: .
      dockerfile: Dockerstartup
    ports:
      - "3001:3000"
    networks:
      - "checklistnetwork"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/checklist?schema=public

volumes:
  checklistdata:
    driver: local

networks:
  checklistnetwork:
    driver: bridge